// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace DragonBones.Animation
{

	/**
	 * The IAnimatable interface defines the methods used by all animatable instance type used by the DragonBones system.
	 * @see dragonBones.Armature
	 * @see dragonBones.animation.WorldClock
	 */


	public interface IAnimatable
	{

		/**
		 * Update the animation using this method typically in an ENTERFRAME Event or with a Timer.
		 * @param	The amount of second to move the playhead ahead.
		 */

		void AdvanceTime(float passedTime);

	}
}

