// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Events;

namespace DragonBones.Events
{
	public class SoundEventManager :EventDispatcher
	{

		private SoundEventManager() { }
		private static SoundEventManager instance;
		public static SoundEventManager Instance
		{
			get
			{
				if(instance == null)
					instance = new SoundEventManager();
				return instance;
			}
		}


	}
}

