// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using DragonBones;

namespace DragonBones.Textures
{
    public class TextureAtlas:ITextureAtlas
    {
        public string Name;
        public Texture Texture;
        public Material Material;

        public TextureAtlas(Texture texture, TextureAtlasData atlasData)
        {
            Name = atlasData.name;
            Texture = texture;
            textureAtlasData = atlasData;

            Shader shader = Shader.Find("Transparent/Depth Ordered Unlit");
            Material = new Material(shader);
            Material.mainTexture = texture;
        }

        public System.Object GetRegion(string name)
        {

            return null;
        }

        public void Dispose()
        {
        }
    }
}

