// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace DragonBones.Utils
{
	public class ConstValues
	{
		public const float ANGLE_TO_RADIAN = (float)Math.PI / 180f;
		
		public const string DRAGON_BONES = "dragonBones";
		public const string ARMATURE = "armature";
		public const string SKIN = "skin";
		public const string BONE = "bone";
		public const string SLOT = "slot";
		public const string DISPLAY = "display";
		public const string ANIMATION = "animation";
		public const string TIMELINE = "timeline";
		public const string FRAME = "frame";
		public const string TRANSFORM = "transform";
		public const string COLOR_TRANSFORM = "colorTransform";
		
		public const string TEXTURE_ATLAS = "TextureAtlas";
		public const string SUB_TEXTURE = "SubTexture";
		
		public const string A_VERSION = "version";
		public const string A_IMAGE_PATH = "imagePath";
		public const string A_FRAME_RATE = "frameRate";
		public const string A_NAME = "name";
		public const string A_PARENT = "parent";
		public const string A_LENGTH = "length";
		public const string A_TYPE = "type";
		public const string A_FADE_IN_TIME = "fadeInTime";
		public const string A_DURATION = "duration";
		public const string A_SCALE = "scale";
		public const string A_OFFSET = "offset";
		public const string A_LOOP = "loop";
		public const string A_EVENT = "event";
		public const string A_SOUND = "sound";
		public const string A_ACTION = "action";
		public const string A_HIDE = "hide";
		public const string A_TWEEN_EASING = "tweenEasing";
		public const string A_TWEEN_ROTATE = "tweenRotate";
		public const string A_DISPLAY_INDEX = "displayIndex";
		public const string A_Z_ORDER = "z";
		public const string A_BLENDMODE = "blendMode";
		public const string A_WIDTH = "width";
		public const string A_HEIGHT = "height";
		public const string A_SCALE_MODE = "scaleMode";
		public const string A_FIXED_ROTATION = "fixedRotation";
		public const string A_X = "x";
		public const string A_Y = "y";
		public const string A_SKEW_X = "skX";
		public const string A_SKEW_Y = "skY";
		public const string A_SCALE_X = "scX";
		public const string A_SCALE_Y = "scY";
		public const string A_PIVOT_X = "pX";
		public const string A_PIVOT_Y = "pY";
		public const string A_ALPHA_OFFSET = "aO";
		public const string A_RED_OFFSET = "rO";
		public const string A_GREEN_OFFSET = "gO";
		public const string A_BLUE_OFFSET = "bO";
		public const string A_ALPHA_MULTIPLIER = "aM";
		public const string A_RED_MULTIPLIER = "rM";
		public const string A_GREEN_MULTIPLIER = "gM";
		public const string A_BLUE_MULTIPLIER = "bM";

		public const string A_SUBTEXTURE = "SubTexture";
	}
}

