// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Com.Viperstudio.Utils;

namespace DragonBones.Objects
{
	public class AnimationData :Timeline
	{
		public uint FrameRate;
		public string Name;
		public int Loop;
		public float TweenEasing;
		
		private Dictionary<string,TransformTimeline>  _timelines;
		public Dictionary<string,TransformTimeline> Timelines
		{
			get { return _timelines; }
		}
		
		private float _fadeTime;
		public float FadeInTime
		{
			get { return _fadeTime; }
			set {
					if(float.IsNaN(value))
					{
						value = 0;
					}
					_fadeTime = value;

				}
		}
	
		public AnimationData()
		{
			Loop = 0;
			TweenEasing = float.NaN;
			
			_timelines = new Dictionary<string, TransformTimeline>();
			
			_fadeTime = 0;
		}
		
		override public void Dispose()
		{

			foreach(KeyValuePair<string, TransformTimeline> timeline in _timelines)
			{
				(timeline.Value as TransformTimeline).Dispose();
			}
			_timelines = null;
		}
		
		public TransformTimeline GetTimeline(string timelineName)
		{
			if(_timelines.ContainsKey(timelineName))
			   return _timelines[timelineName] as TransformTimeline;
			else
				return null;
		}
		
		public void AddTimeline(TransformTimeline timeline, string timelineName)
		{
			if(timeline == null)
			{
				throw new ArgumentException();
			}

			_timelines[timelineName] = timeline;
		}
	}
}

