// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Com.Viperstudio.Utils;

namespace DragonBones.Objects
{
	public class AtlasData
	{
		public String Name;

		private Dictionary<string, TextureData> _textureDatas;

		public AtlasData ()
		{
		}

		public void AddTextureData(TextureData textureData)
		{
			if(_textureDatas == null)
			{
				_textureDatas = new Dictionary<string, TextureData>();
			}
			_textureDatas.Add(textureData.Name, textureData);
		}

		public TextureData GetTextureData(string name)
		{
			if(_textureDatas!=null)
			{
				if(_textureDatas.ContainsKey(name))
				{
					return _textureDatas[name];
				}
			}
			return null;
		}

	}

	public class TextureData
	{
		
		public string Name;
		public float X, Y, Width, Height;
	
	}
}

