// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DragonBones.Utils;
using Com.Viperstudio.Utils;

namespace DragonBones.Objects
{
	public class AtlasDataParser
	{

		public AtlasDataParser ()
		{
		}


		public static AtlasData ParseAtlasData(Dictionary<string, Object> rawData)
		{
			if(rawData == null)
			{
				throw new ArgumentException();
			}

			AtlasData data = new AtlasData();
			data.Name = rawData[ConstValues.A_NAME] as String;

			foreach(Dictionary<String, Object> textureObject in rawData[ConstValues.A_SUBTEXTURE] as List<Object>)
			{
				
				data.AddTextureData(parseTextureData(textureObject as Dictionary<string, object>));
			}
			
			return data;

		}

		private static TextureData parseTextureData(Dictionary<string, object> textureRawData)
		{
			TextureData textureData = new TextureData();
			textureData.Name = textureRawData[ConstValues.A_NAME].ToString();	
			textureData.X = float.Parse(textureRawData[ConstValues.A_X].ToString());
			textureData.Y = float.Parse(textureRawData[ConstValues.A_Y].ToString());
			textureData.Width = float.Parse(textureRawData[ConstValues.A_WIDTH].ToString());
			textureData.Height = float.Parse(textureRawData[ConstValues.A_HEIGHT].ToString());
			return textureData;
			
		}



	}
}

