// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class RectangleData : IAreaData
		{
	
		public float width;
		public float height;


		public Transform transform;
		public Point pivot;

		public RectangleData ()
	    {
			areaType = IAreaData.AreaType.AT_RECTANGLE;
			width = 0.0f;
			height = 0.0f;
		}


		}
}

