// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace DragonBones
{
		public class SkinData
		{

	
		public string name;
		public List<SlotData> slotDataList = new List<SlotData>();

				public SkinData ()
				{
				}



	public SlotData getSlotData(string slotName) 
	{
		for (int i = 0; i < slotDataList.Count; ++i)
		{
			if (slotDataList[i].name == slotName)
			{
				return slotDataList[i];
			}
		}
		
		return null;
	}

	public	void dispose()
		{
			for (int i = 0; i < slotDataList.Count; ++i)
			{
				slotDataList[i].dispose();
				//delete slotDataList[i];
			}
			
			slotDataList.Clear();
		}

	}
}

