// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones.Objects
{
	public class TransformTimeline :Timeline
	{
		public static TransformTimeline HIDE_TIMELINE = new TransformTimeline();
		
		public bool Transformed;
		
		public DBTransform OriginTransform;
		public Point OriginPivot;
		
		private float _offset;
		public float Offset
		{
			get { return _offset; }
			set {

				float r = 0f;
				if(value!=float.NaN&&value!=0) r = value;

				_offset = r % 1;
				if(_offset < 0)
				{
					_offset += 1;
				}
				 
				}
		}
	
		
		public TransformTimeline()
		{

			OriginTransform = new DBTransform();
			OriginPivot = new Point();
			_offset = 0;
		}
		
		override public void Dispose()
		{
			if(this == HIDE_TIMELINE)
			{
				return;
			}
			base.Dispose();
			OriginTransform = null;
			OriginPivot = null;
		}
	}
}

