// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class TransformTimeline: Timeline
		{
        public static TransformTimeline HIDE_TIMELINE = new TransformTimeline();
        public bool transformed;
		public float offset;

		public string name;
		public DBTransform originTransform = new DBTransform();
		public Point originPivot = new Point();

		public TransformTimeline ()
		{
			offset = 0.0f;
			transformed = false;
		}


		}
}

