// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class DBObject
		{

	
		public	bool inheritRotation;
		public bool inheritScale;
		
		public string name;
		public DBTransform global = new DBTransform();
		public DBTransform origin = new DBTransform();
		public DBTransform offset = new DBTransform();
		public Matrix globalTransformMatrix = new Matrix();
		
		public object userData;
		
	
	    protected	bool _visible;
		
		public Armature _armature;
		public Bone _parent;


		public DBObject ()
		{
			_visible = true;
			_armature = null;
			_parent = null;
			offset.ScaleX = offset.ScaleY = 1.0f;
			userData = null;

		}

	
		public 	virtual bool getVisible()
		{
			return _visible;
		}
		public virtual void setVisible(bool visible)
		{
			_visible = visible;
		}

		
		public virtual Armature getArmature()
		{
			return _armature;
		}
		public virtual Bone getParent()
		{
			return _parent;
		}

		
	
		public virtual void setArmature(Armature armature)
		{
			if (_armature!=null)
			{
				_armature.removeObject(this);
			}
			
			_armature = armature;
			
			if (_armature!=null)
			{
				_armature.addObject(this);
			}
		}

		public virtual void setParent(Bone bone)
		{
			_parent = bone;
		}


		}
}

