// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace DragonBones.Core
{
	public class DragonBones
	{

		public const string DATA_VERSION = "2.3";
		public const string VERSION = "2.4";
		public const int VERSION_NUMBER = 2400;

		public DragonBones ()
		{
		}
	}
}

