// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Com.Viperstudio.Geom
{
		public class ColorTransform
		{
			public float AlphaOffset = 0f;
			public float RedOffset = 0f;
			public float GreenOffset = 0f;
			public float BlueOffset = 0f;

			public float AlphaMultiplier = 0f;
			public float RedMultiplier = 0f;
			public float GreenMultiplier = 0f;
			public float BlueMultiplier = 0f;

				public ColorTransform ()
				{
				}
		}
}

