// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Utils;

namespace Com.Viperstudio.Geom
{

	public class Matrix
	{

		public Com.Viperstudio.Utils.Matrix matrix;

		public float A { 
			get { return (float)matrix.mat [0, 0]; }
			set { matrix.mat [0, 0] = value; }
		}

		public float B { 
			get { return (float)matrix.mat [0, 1] ; }
			set { matrix.mat [0, 1]  = value; }
		}

		public float C { 
			get { return (float)matrix.mat [1, 0] ; }
			set { matrix.mat [1, 0]  = value; }
		}

		public float D { 
			get { return (float)matrix.mat [1, 1]; }
			set { matrix.mat [1, 1] = value; }
		}

		public float Tx { 
			get { return (float)matrix.mat [2, 0] ;}
			set { matrix.mat [2, 0] = value; }
		}

		public float Ty { 
			get { return (float)matrix.mat [2, 1]; }
			set { matrix.mat [2, 1] = value; }
		}



		public Matrix (float a = 1f, float b = 0f, float c = 0f, float d = 1f, float tx =0f, float ty = 0f)
		{
			matrix = new Com.Viperstudio.Utils.Matrix (3, 3);
			matrix.mat [0, 0] = a;
			matrix.mat [1, 0] = c;
			matrix.mat [2, 0] = tx;
			matrix.mat [0, 1] = b;
			matrix.mat [1, 1] = d;
			matrix.mat [2, 1] = ty;
			matrix.mat [0, 2] = 0;
			matrix.mat [1, 2] = 0;
			matrix.mat [2, 2] = 1;


		}

		public void Invert()
		{

			matrix = matrix.Invert ();

		

	    }

		public void StrassenMultiple (Com.Viperstudio.Geom.Matrix m)
		{
			matrix = matrix * m.matrix;
		}


	}
}

