// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Com.Viperstudio.Geom
{
		public class Point
		{
		 
		  public float X;
		  public float Y;


		  public Point(float x = 0, float y = 0)
		  {
			X = x;
			Y = y;
		  }

		}
}

