// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
using DragonBones.Objects;

namespace DragonBones.Display
{
		public interface IDisplayBridge
		{

		bool Visible { get; set;}

		
		/**
		 * Indicates the original display object relative to specific display engine.
		 */
		Object Display { get; set; }

		/**
		 * Cleans up resources used by this IDisplayBridge instance.
		 */
		void Dispose();
		
		/**
		 * Updates the transform of the display object
		 * @param	matrix
		 * @param	transform
		 */
		void UpdateTransform(Matrix matrix, DBTransform transform);
		
		/**
		 * Updates the color of the display object
		 * @param	a
		 * @param	r
		 * @param	g
		 * @param	b
		 * @param	aM
		 * @param	rM
		 * @param	gM
		 * @param	bM
		 */
		void UpdateColor(
			float aOffset, 
			float rOffset, 
			float gOffset, 
			float bOffset, 
			float aMultiplier, 
			float rMultiplier, 
			float gMultiplier, 
			float bMultiplier
		);
		
		/**
         * Update the blend mode of the display object
         * @param blendMode The blend mode to use. 
         */
		void UpdateBlendMode(string blendMode);
		
		/**
		 * Adds the original display object to another display object.
		 * @param	container
		 * @param	index
		 */
		void AddDisplay(Object container, float index = -1f);
		
		/**
		 * remove the original display object from its parent.
         */

		void RemoveDisplay();


		}
}

