// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Com.Viperstudio.Utils
{
	public class Logger
	{
		public Logger ()
		{

		}


	    public static void Log(string str)
	    {
			Debug.Log (str);
	    }
	}
}

