// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace  Com.Viperstudio.Geom
{
		public class Transform
		{

	
		public	float X;
		public float Y;
		public float SkewX;
		public float SkewY;
		public float ScaleX;
		public float ScaleY;

				public Transform ()
				{
						
				}


			

		}
}

