// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones
{
	public class TextureData
	{

		public bool rotated;

		
		public string name;
		public Rectangle region = new Rectangle();	
		public Rectangle frame = new Rectangle();
		
		public TextureData ()
		{
			rotated = false;
			frame = null;
		}

		public void dispose()
		{
			if (frame!=null)
			{
				//delete frame;
				frame = null;
			}
		}

		
	}
}

