// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DragonBones.Utils;
using Com.Viperstudio.Utils;

namespace DragonBones
{
	public class AtlasDataParser
	{

		public AtlasDataParser ()
		{
		}


		public static TextureAtlasData ParseAtlasData(Dictionary<string, Object> rawData)
		{
			if(rawData == null)
			{
				throw new ArgumentException();
			}

            TextureAtlasData data = new TextureAtlasData();
			data.name = rawData[ConstValues.A_NAME] as String;

			foreach(Dictionary<String, Object> textureObject in rawData[ConstValues.A_SUBTEXTURE] as List<Object>)
			{
				data.textureDataList.Add(parseTextureData(textureObject as Dictionary<string, object>));
			}
			
			return data;

		}

		private static TextureData parseTextureData(Dictionary<string, object> textureRawData)
		{
			TextureData textureData = new TextureData();
			textureData.name = textureRawData[ConstValues.A_NAME].ToString();	
			textureData.region.x = float.Parse(textureRawData[ConstValues.A_X].ToString());
			textureData.region.y = float.Parse(textureRawData[ConstValues.A_Y].ToString());
			textureData.region.width = float.Parse(textureRawData[ConstValues.A_WIDTH].ToString());
			textureData.region.height = float.Parse(textureRawData[ConstValues.A_HEIGHT].ToString());
			return textureData;
			
		}



	}
}

