// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml;

namespace DragonBones.Objects
{
	public class DataParser
	{


		
		public static SkeletonData parseData(Object rawData)
		{
			if(rawData is XmlNode)
			{
				//return XMLDataParser.ParseSkeletonData(rawData as XmlNode);
			}
			else
			{
				return ObjectDataParser.ParseSkeletonData(rawData as Dictionary<string, object>);
			}
			return null;
		}
	}
}

