// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;

namespace DragonBones
{
	public class DisplayData
	{

		public string name;
		public DragonBones.DisplayType type;
		public DBTransform transform = new DBTransform();
		public Point pivot = new Point();

		public DisplayData ()
		{
			type = DragonBones.DisplayType.DT_IMAGE;
		}
	}
}

