// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace DragonBones
{
		public class Frame
		{
	     public enum  FrameType {FT_FRAME, FT_TRANSFORM_FRAME};  
		 public	int position;
		 public int duration;
		
		public FrameType frameType;
		public string action = "";
		public string evt = "";
		public string sound = "";
		public string eventParameters;
		
		public Object eventParametersParsed;

		  public Frame ()
		  {
			position = 0;
			duration = 0;
			frameType = FrameType.FT_FRAME;		
			eventParametersParsed = null;
		  }


		public void dispose() 
		{
			if (eventParametersParsed!=null)
			{
				//delete eventParametersParsed;
				eventParametersParsed = null;
			}
		}

		}
}

