// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace DragonBones.Objects
{
	public class Frame
	{
		public float Position;
		public float Duration;
		
		public string Action;
		public string Evt;
		public string Sound;
		
		public Frame()
		{
			Position = 0f;
			Duration = 0f;
		}
		
		public virtual void Dispose()
		{
		}
	}
}

