// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace DragonBones
{
		public class IAreaData
		{

		public IAreaData.AreaType areaType;
		public string name;

		public enum  AreaType {AT_ELLIPSE, AT_RECTANGLE};
	
		public void dispose(){}

		}
}

