// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DragonBones.Objects
{
	public class SlotData
	{
		public string Name;
		public string Parent;
		public float ZOrder;
		public string BlendMode;
		
		private List<DisplayData> _displayDataList;
		public List<DisplayData> DisplayDataList
		{
			get { return _displayDataList; }
		}
		
		public SlotData()
		{
			_displayDataList = new List<DisplayData>();
			ZOrder = 0;
			BlendMode = "normal";
		}
		
		public void Dispose()
		{
			int i = _displayDataList.Count;
			while(i -- >0)
			{
				_displayDataList[i].Dispose();
			}

			_displayDataList.Clear();
	
		}
		
		public void AddDisplayData(DisplayData displayData)
		{
			if(displayData == null)
			{
				throw new ArgumentException();
			}
			if (_displayDataList.IndexOf(displayData) < 0)
			{

				_displayDataList.Add(displayData);

			}
			else
			{
				throw new ArgumentException();
			}
		}
		
		public DisplayData GetDisplayData(string displayName)
		{
			int i = _displayDataList.Count;
			while(i -- >0)
			{
				if(_displayDataList[i].Name == displayName)
				{
					return _displayDataList[i];
				}
			}
			
			return null;
		}
	}
}

