// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class TransformFrame: Frame
		{
	
		public bool visible;
		public bool tweenScale;
		public int tweenRotate;
		public int displayIndex;
		public float zOrder;
		// NaN:no tween, 10:auto tween, [-1, 0):ease in, 0:line easing, (0, 1]:ease out, (1, 2]:ease in out
		public float tweenEasing;

		public DBTransform global = new DBTransform();
		public DBTransform transform = new DBTransform();
		public Point pivot = new Point();
		public Point scaleOffset = new Point();
		public ColorTransform color = new ColorTransform();


		public TransformFrame ()
		{
			visible = true;
			tweenScale = true;
			tweenRotate = 0;
			displayIndex = 0;
			zOrder = 0.0f;
			tweenEasing = DragonBones.NO_TWEEN_EASING;
			frameType = Frame.FrameType.FT_TRANSFORM_FRAME;
			color = null;

	    }
		}
}

