// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Events;
using DragonBones.Animation;

namespace DragonBones.Events
{
	public class FrameEvent :Event
	{
		public static string MOVEMENT_FRAME_EVENT
		{
			get { return  ANIMATION_FRAME_EVENT; }
		}
		
		/**
		 * Dispatched when the animation of the armatrue enter a frame.
		 */
		public const string ANIMATION_FRAME_EVENT = "animationFrameEvent";
		
		/**
		 * 
		 */
		public const string BONE_FRAME_EVENT ="boneFrameEvent";
		
		/**
		 * The entered frame label.
		 */
		public string FrameLabel;
		
		public Bone Bone;
		
		/**
		 * The armature that is the target of this event.
		 */
		public Armature Armature
		{
			get { return Target as Armature; }
		}
		
		/**
		 * The animationState instance.
		 */
		public AnimationState AnimationState;
		
		/**
		 * Creates a new FrameEvent instance.
		 * @param	type
		 * @param	cancelable
		 */
		public FrameEvent(string type) :base(type)
		{

		}
		
		/**
		 * @private
		 *
		 * @return An exact duplicate of the current object.
		 */
		override public Event clone()
		{
			FrameEvent evt = new FrameEvent(this.EventType);
			evt.AnimationState = AnimationState;
			evt.Bone = Bone;
			evt.FrameLabel = FrameLabel;
			return evt;
		}
	}
}

