// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Events;
using DragonBones.Animation;

namespace DragonBones.Events
{
	public class SoundEvent :Event
	{
		/**
		 * Dispatched when the animation of the animation enter a frame containing sound labels.
		 */
		public const string SOUND = "sound";
		
		/**
		 * The armature that is the target of this event.
		 */
		public Armature Armature;
		
		public AnimationState AnimationState;
		
		public string Sound;
		
		/**
		 * Creates a new SoundEvent instance.
		 * @param	type
		 * @param	cancelable
		 */
		public SoundEvent(string type) : base(type)
		{

		}
		
		/**
		 * @private
		 */
		override public Event clone()
		{
			SoundEvent evt = new SoundEvent(EventType);
			evt.Armature = Armature;
			evt.AnimationState = AnimationState;
			evt.Sound = Sound;
			return evt;
		}
	}
}

