// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Com.Viperstudio.Events
{
	public class Event :EventArgs
	{
		public String EventType;

		public EventDispatcher Target;

		public Event (string eventType) :base()
		{
			this.EventType = eventType;
		}

		public virtual Event clone()
		{
			return this;
		}

	}
}

